Repository ghg-projects/music-rival-mobile, pull requests merged in 2023-09, with the labels that each got.

#6 Update .gitignore
  .gitignore
Labels: chore

#12 update pr template
  .github/pull_request_template.md
Labels: chore

#14 set up supabase
  package.json
  supabase/.gitignore
  supabase/config.toml
  supabase/migrations/20230923202757_remote_schema.sql
  supabase/seed.sql
  yarn.lock
Labels: enhancement

#16 Refined Logon Screen
  .github/pull_request_template.md
  app/(signon)/index.tsx
  app/_layout.tsx
  components/SignOnScreen/index.tsx
  constants/Haptics.ts
  package.json
  shared/Button.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement

#17 Hotfixes for signon PR
  app/signon.tsx
  components/SignOnScreen/index.tsx
Labels: bug

#21 setup a custom alias for directories
  app/signon.tsx
  babel.config.js
  components/SignOnScreen/index.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: chore

#22 20 add supabase authentication
  .gitignore
  .prettierignore
  app/(tabs)/index.tsx
  app/_layout.tsx
  babel.config.js
  components/SignOnScreen/index.tsx
  lib/supabase.ts
  package.json
  shared/Button.tsx
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement
